casual/urls.py
from django.urls import path
from . import views

app_name = 'casual'

urlpatterns = [
    path('', views.tanyakan, name='casual'),
    # dilanjutkan ...
]

formal/urls.py
from django.urls import path
from . import views

app_name = 'formal'

urlpatterns = [
    path('', views.tanyakan, name='formal'),
    # dilanjutkan ...
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.toHome, name='home'),
    path('kritik/', views.listKritik, name='kritik'),
    # dilanjutkan ...
]

sport/urls.py
from django.urls import path
from . import views

app_name = 'sport'

urlpatterns = [
    path('', views.tanyakan, name='sport'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('casual/', include('casual.urls')),
    path('formal/', include('formal.urls')),
    path('sport/', include('sport.urls')),
    path('description/', include('description.urls')),
    path('alamat/', include('alamat.urls')),
]

home/models.py
from django.db import models

# Create your models here.
class Sarannya(models.Model):
    saran=models.TextField(blank=False, null=False)
    date=models.DateTimeField(auto_now_add=True)

home/forms.py
from django import forms
from . import models

class KritikForm(forms.ModelForm):
    saran=forms.CharField(widget=forms.Textarea(attrs={
        "style":"width:1108px; height:200px; resize:none",
        "class":"form-control",
        "required":True,
        "placeholder":"Masukkan saran anda",
    }), label="")
    class Meta:
        model=models.Sarannya
        fields=['saran']

home/views.py
from django.shortcuts import render, redirect
from .forms import KritikForm
from .models import Sarannya
from . import forms
from datetime import datetime, date

def toHome(request):
    if request.method=='POST':
        form=forms.KritikForm(request.POST)
        if form.is_valid():
            saran=form.cleaned_data['saran']
            formSaran = Sarannya(saran=saran)
            formSaran.save()
            #Task.objects.all().delete()
            return redirect('home:home')
        else:
            return render(request, "home.html",{'form':form})
    form=forms.KritikForm()
    return render(request, "home.html",{'form':form})
# Create your views here.

def listKritik(request):
	return render(request, 'ListKritik.html')

def removeKritik(request, saran_id):
    form=Sarannya.objects.get(id=saran_id)
    form.delete()
    return redirect('list')

home/templates/ListKritik.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>WIL& Shoes Shop</title>
    </head>
        <style>
            table {
                width: 80%;
            }
            td, th {
                text-align: left;
                padding: 8px;
            }
            .other1{
                width: 450px;
            }
            .other2{
                width: 50px;
            }
        </style>
    <body>
        <div id="HOME"></div>
          <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>
        <div class="forms">
        </br>
            <p style="text-align: center; font-size: 40px">List Kritik/Saran</p>
            <table bgcolor="white" align="center" style="margin-top: 40px; margin-bottom: 40px; font-size: 24px;">
                {% for form in forms %}
                <div class="form">
                    <tr>
                        <th>{{ form.date }}</th>
                    </tr>
                    <tr>
                        <td class="othe1">{{ form.saran }}</td>
                        <td class="other2"><a href="/removeKritik/{{form.id}}" style="text-decoration:none; color:red">Remove</a></td>
                    </tr>
                    <tr>
                        <td></br></td>
                    </tr>
                </div>
                {% endfor %}
            </table>
        </div>
    </body>
</html>

home/templates/home.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>WIL& Shoes Shop</title>
  </head>
    <style>
      body{
          background-repeat: no-repeat;
          background-color: #F7F6E7;}
    </style>
  <body>
    <!-- <h1>Hello, world!</h1> -->
    <div id="HOME"></div>
    <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="#CATEGORIES" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>

    <div class="container" style="margin-top: 5%; font-size: 24px;">
      <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="4"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="5"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'photos/olahraga1.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Sport shoes</h5>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'photos/olahraga2.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Sport shoes</h5>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'photos/casual1.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Casual shoes</h5>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'photos/casual2.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Casual shoes</h5>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'photos/formal1.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Formal shoes</h5>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static 'photos/formal2.jpg' %}" class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
              <h5>Formal Shoes</h5>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <p id="CATEGORIES"></br></p>
      <div class="row">
        <div class="col-sm">
          <div class="row-sm" style="margin-top: 5%; margin-bottom: 2%; font-size: 32px;">
            Categories
          </div>
          <div class="row justify-content-between">
            <div class="col"><a href="{% url 'casual:casual' %}">
              <img src="{% static 'photos/sepatucasual1.jpg' %}" width="300px" height="auto"></a>
              </br>Casual
            </div>
            <div class="col"><a href="{% url 'formal:formal' %}">
              <img src="{% static 'photos/sepatuformal.png' %}" width="300px" height="auto"></a>
              </br>Formal
            </div>
            <div class="col"><a href="{% url 'sport:sport' %}">
              <img src="{% static 'photos/sepatusport.jpg' %}" width="300px" height="auto"></a>
              </br>Sport
            </div>
          </div>
        </div>
      </div>
      <div class="row-sm" style="text-align: center; margin-top: 5%; line-height: 40px;">
        </br>Ada kritik/saran? Silahkan isi kolom dibawah ini</br>
        <form class="site-form" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <table align="center" style="color: white; font-size:24px">
            {{ form.as_table }}
          </table>
          <p style="text-align: center"><button type="submit">&emsp;Kirim&emsp;</button></p>
        </form>
      </div>
    </div>
    </br></br>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>