alamat/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'alamat'

urlpatterns = [
    path('', views.alamat, name='alamat'),
    path('alamatAdmin/', views.alamatAdmin, name='alamatAdmin'),
    path('submitted/', views.submitted, name='submitted'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.AlamatDelete.as_view(), name='delete'),
]

description/urls.py
from django.urls import path
from . import views


app_name = 'description'

urlpatterns = [
    path('', views.index, name='index'),
 
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.toHome, name='home'),
    path('kritik/', views.listKritik, name='kritik'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('casual/', include('casual.urls')),
    path('formal/', include('formal.urls')),
    path('sport/', include('sport.urls')),
    path('description/', include('description.urls')),
    path('alamat/', include('alamat.urls')),
]

description/models.py
from django.db import models

# Create your models here.

class Description(models.Model):
    dropchoice = (('40','40'),('41','41'),('42','42'),('43','43'),('44','44'))
    ukuran = models.CharField(max_length=20, choices=dropchoice,default='40')
    catatan = models.CharField(max_length=100)
    jumlah = models.IntegerField(default=1)

description/forms.py
from django import forms
from . import models

class DescForms(forms.ModelForm):
    class Meta:
        model = models.Description
        fields = ['ukuran','catatan','jumlah']

description/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import DescForms
from .models import Description
from django.views.decorators.http import require_POST

# Create your views here.

def index(request):
    list_form = Description.objects.order_by('jumlah')
    form = DescForms()
    content = {'list_form': list_form , 'form' : form }
    return render(request,'descriptionc1.html', content )

def tambahForms(request):
	form = DescForms(request.POST)

	if form.is_valid():
		descBaru = Description(jumlah =request.POST['jumlah'],ukuran=request.POST['ukuran'],catatan=request.POST['catatan'])
		descBaru.save()

	return redirect('description:index')

description/templates/descriptionc1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<body style="background-color: #F7F6E7; padding-bottom: 100px;">
<div>
    <div id="HOME"></div>
      <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="#CATEGORIES" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>
</div>

<div>
    <img src="{% static 'images/sepatucasual1.jpeg' %}" alt="" class="fotosepatu">
    <span><h1 style="text-align: center;font-family: 'Acme';">~ Rp1.200.000 ~</h1></span>
</div>

<div class="container">
    <div class="row" id="bgcolorr">
        <div class="col-sm" id="borderdotted" >
            <h2>DESKRIPSI PRODUK</h2>
            <hr style="border: 2px solid green;
                border-radius: 5px;">
            <p>Sepatu memiliki 2 warna yang berbeda yaitu putih dan hitam.
                sepatu ini memunyai keindahan yang cukup mempersona. sepatu ini tidak bertali.
                sepatu ini memunyai manfaat yang sangat lah banyak.</p>
        </div>
        <div class="col-sm" id="borderdotted">
            <h2>PEMBELIAN</h2>
            <hr style="border: 2px solid green;
                border-radius: 5px;">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <h3>Ukuran :</h3>
                        <form  method="POST" role="form">
                            {% csrf_token %}
                            {{form.ukuran}}

                    </div>
                    <div class="col-sm">

                        <h3>Jumlah :</h3>
                        {{form.jumlah}}

                        <h4>Catatan untuk penjual :</h4>
                        {{form.catatan}}
                        <br>
                       <a href="{% url 'alamat:alamat' %}"> <button type="button" class="btn btn-dark mt-2">Lanjut </button> </a>
                        </form>
                        <br><br><br>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


</body>
</html>