alamat/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'alamat'

urlpatterns = [
    path('', views.alamat, name='alamat'),
    path('alamatAdmin/', views.alamatAdmin, name='alamatAdmin'),
    path('submitted/', views.submitted, name='submitted'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.AlamatDelete.as_view(), name='delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.toHome, name='home'),
    path('kritik/', views.listKritik, name='kritik'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('casual/', include('casual.urls')),
    path('formal/', include('formal.urls')),
    path('sport/', include('sport.urls')),
    path('description/', include('description.urls')),
    path('alamat/', include('alamat.urls')),
]

alamat/models.py
from django.db import models


class Form(models.Model):
     
    Nama_Pembeli = models.CharField(max_length=50)
    Nama_Produk = models.CharField(max_length=50)
    Nomor_Handphone = models.CharField(max_length=50)
    Nomor_Telepon = models.CharField(max_length=50)
    Alamat_Lengkap = models.TextField(max_length=500)

alamat/forms.py
from django import forms
from .models import Form


class PostForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = '__all__'
        # widgets = {
        #     'tanggal' : forms.SelectDateWidget(),
        #     'jam' : forms.TimeInput(attrs={
        #         'class' : 'form-control',
        #         'type' : 'time'
        #     }),
        # }

alamat/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Form
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

class AlamatDelete(DeleteView):
        model = Form
        success_url = reverse_lazy('alamat:alamatAdmin')

def alamat(request):
    post = Form.objects.all()
    post_form = PostForm(request.POST or None)


    if request.method == 'POST':
        # if 'id' in request.POST:
        #     Form.objects.get(id=request.POST['id']).delete()
        #     return redirect('jadwal:jadwal')
        
        if post_form.is_valid():
            post_form.save()
            return redirect('alamat:submitted')

    context = {
        'post_form' : post_form,
        'posting': post 
    }
    return render(request, 'alamat.html',context)


def alamatAdmin(request):
    post = Form.objects.all()
    post_form = PostForm(request.POST or None)


    # if request.method == 'POST':
    #     # if 'id' in request.POST:
    #     #     Form.objects.get(id=request.POST['id']).delete()
    #     #     return redirect('jadwal:jadwal')
        
    #     if post_form.is_valid():
    #         post_form.save()
    #         return redirect('alamat:alamatAdmin')

    context = {
        'post_form' : post_form,
        'posting': post 
    }
    return render(request, 'alamatAdmin.html',context)

def submitted(request):
   
    return render(request, 'submitted.html')

alamat/templates/alamat.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>tugas kelompok 1</title>
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    
</head>
<body>
        <div>
               <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>

            </div>
        <h1 style= "position: absolute; font-size: 2vw; margin-left: 10vw; margin-top: 5vw">Halaman Pembelian</h1>

        <form action="" method="POST"style="margin: 10vw 10vw">
            {% csrf_token %}
            <table>
                {{post_form.as_table}}
            </table>
            <button type="submit" style= "position: absolute; margin-left: 30vw; margin-top: 2vw">Submit</button>

        </form>
    
</body>


</html>

alamat/templates/alamatAdmin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>tugas kelompok 1</title>
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
          
        table#t01 {  
        border: 1px solid black;
        border-collapse: collapse;
        margin-left: 2vw;
        }
        
    </style>
</head>
<body>
        <div>
                <nav class="navbar navbar-expand-sm" style= "background-color:#455650" >
                    <!-- Brand/logo -->
                    <a class="navbar-brand" href="#">
                        <img src="{% static "images/logo.jpg" %}" alt="logo" style="width:116px;height: 42px;">
                    </a>
                    <!-- Links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:home' %}">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">CATEGORY</a>
                        </li>
                    </ul>
                </nav>
            </div>
        <br>
        
        <table id= "t01" style="text-align: center;">
            <tr>
                <th style= "border: 1px solid black; padding: 5px 5px; width: 15vw">Nama Pembeli</th>
                <th style= "border: 1px solid black; padding: 5px 5px; width: 15vw">Nama Produk</th> 
                <th style= "border: 1px solid black; padding: 5px 5px; width: 15vw">Nomor Handphone</th>
                <th style= "border: 1px solid black; padding: 5px 5px; width: 15vw">Nomor Telepon</th>
                <th style= "border: 1px solid black; padding: 5px 5px; width: 20vw">Alamat Lengkap</th>
            </tr>
        </table>
      
        
        {% for a in posting %}
        <table style= "margin-left: 2vw; margin-top: 3vw; text-align: center">
            
            <tr>
                <td style= "border: 1px solid black; padding: 5px 25px; width: 15vw; max-width: 15vw">{{a.Nama_Pembeli}}</td>
                <td style= "border: 1px solid black; padding: 5px 25px; width: 15vw; max-width: 15vw">{{a.Nama_Produk}}</td>
                <td style= "border: 1px solid black; padding: 5px 25px; width: 15vw; max-width: 15vw">{{a.Nomor_Handphone}}</td>
                <td style= "border: 1px solid black; padding: 5px 25px; width: 15vw; max-width: 15vw">{{a.Nomor_Telepon}}</td>
                <td style= "border: 1px solid black; padding: 5px 25px; width: 20vw; max-width: 20vw">{{a.Alamat_Lengkap}}</td>
  
            </tr>
        </table>
        <form action="{% url 'alamat:delete' a.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="a_id" value="{{ a.id }}"/>
                <button type="" class="btn-sm col-2" style= "position: absolute; margin-left: 2vw" >Hapus</button> 
        </form>
        {% endfor %}
   
</body>


</html>

alamat/templates/submitted.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>tugas kelompok 1</title>
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    
</head>
<body>
        <div>
                <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>

            </div>
        <h1 style= "position: absolute; font-size: 4vw; margin: 40vw; margin-top: 5vw">Terimakasih</h1>
        <br>
        <br>
        <p style= "position: absolute; text-align: center; font-size: 2vw; margin: 5vw; margin-top: 10vw">
            Admin kami akan menghubungi anda via WA atau SMS untuk memberi tahu total harga dan ongkos kirim pesanan anda, maksimal 1 x 24 jam.</p>
    
        <form action="{% url 'home:home' %}">
            <button type="submit" style= "position: absolute; font-size: 2vw; margin: 48vw; margin-top: 20vw">Back</button>
        </form>
    
</body>


</html>