casual/urls.py
from django.urls import path
from . import views

app_name = 'casual'

urlpatterns = [
    path('', views.tanyakan, name='casual'),
    # dilanjutkan ...
]

description/urls.py
from django.urls import path
from . import views


app_name = 'description'

urlpatterns = [
    path('', views.index, name='index'),
 
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.toHome, name='home'),
    path('kritik/', views.listKritik, name='kritik'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('casual/', include('casual.urls')),
    path('formal/', include('formal.urls')),
    path('sport/', include('sport.urls')),
    path('description/', include('description.urls')),
    path('alamat/', include('alamat.urls')),
]

casual/models.py
from django.db import models

class Pertanyaan(models.Model):
	nama = models.CharField(max_length=100)
	kota = models.CharField(max_length=50)
	isi = models.CharField(max_length=1000)

	def __str__(self):
		return self.nama

casual/forms.py
from . import models
from django import forms

class FormTanya(forms.ModelForm):
                nama = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "askfields full",
                "required" : True,
                "placeholder":"Nama Lengkap",
                }))
                kota = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "askfields full",
                "required" : True,
                "placeholder":"Kota",
                }))
                isi = forms.CharField(widget=forms.Textarea(attrs={
                "class" : "askfields full",
                "required" : True,
                "placeholder":"Pertanyaan",
                }))

                class Meta:
                                model = models.Pertanyaan
                                fields = ["nama", "kota", "isi"]

casual/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import FormTanya
from .models import Pertanyaan

# Create your views here.

def tanyakan(request):
    form = FormTanya()
    if request.method =="POST":
        form=FormTanya(request.POST)
        if form.is_valid():
            form.save()
            return redirect('casual:casual')
    return render(request, "kategori.html", {'form':form})

casual/templates/kategori.html
{% load static %}

<html>
<head>
<title> Shoes Categories </title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">     
  <style>

nav{
    background-color:455650;
  }
  .nav-link{
    color:white;
  }

  body{
    background-color:F7F6E7; 
  }

  .container-fluid img{
    padding:10px;
  }
</style>


</head>



<body>
<div id="HOME"></div>
     <nav class="navbar navbar-expand-xl navbar-light bg sticky-top" style="background-color: #455650; font-size: 24px; color: white;">
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'photos/WIL.jpg' %}" width="175px" height="auto"></a>
        <div class="collapse navbar-collapse" id="collapse_target" style="margin-left:5%">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>    
                <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}" style="margin-left:50%">Categories</a></li>
            </ul>
        </div>
    </nav>


<div class="container-fluid" style="padding:20px">


    <br/>
   <h1 style="margin:20px"> Sepatu Casual </h1>
  <div class="row">
    <div class="col">
    <a class="nav-link" href="{% url 'description:index' %}"><img src="{% static 'casual1.jpg' %}" width="350" height="280" title="CS-01" alt="Sepatu 1"> </a>
    </div>

    <div class="col">
      <a class="nav-link"href="{% url 'description:index' %}">
    <img src="{% static 'casual2.jpg' %}" width="350" height="280" title="CS-02" alt="Sepatu 2"></a>
    </div>

    <div class="col">
      <a class="nav-link" href="{% url 'description:index' %}">
    <img src="{% static 'casual3.jpg' %}" width="350" height="280" title="CS-03" alt="Sepatu 3">
  </a>
    </div>

    <div class="col">
      <a class="nav-link" href="{% url 'description:index' %}">
    <img src="{% static 'casual4.jpg' %}"  width="350" height="280" title="CS-04" alt="Sepatu 4">
  </a>
    </div>


    <div class="col">
      <a class="nav-link" href="{% url 'description:index' %}">
    <img src="{% static 'casual5.jpg' %}"  width="350" height="280" title="CS-05" alt="Sepatu 5">
  </a>
    </div>


    <div class="col">
      <a class="nav-link" href="{% url 'description:index' %}">
    <img src="{% static 'casual6.jpg' %}"  width="350" height="280" title="CS-06" alt="Sepatu 6">
  </a>
    </div>

</div>

<form method="POST" class="form" style="padding:20px;margin-top: 50px">
  <h2> Tanya jawab </h2>
  {% csrf_token %}
  <p>Nama</p>
    {{ form.nama }}
    <p><br/>Kota</p>
    {{ form.kota }}
    <p><br/>Pertanyaan</p>
    {{ form.isi }}
    <p><br/></p>
       <div class="full">
                <input type="submit" class="button" value="Submit" />
            </div>
</form>




</body>
</html>